export const GET_ALL_ITEMS_STARTED = "GET_ALL_ITEMS_STARTED";
export const GET_ALL_ITEMS_SUCCESS = "GET_ALL_ITEMS_SUCCESS";
export const GET_ALL_ITEMS_FAILURE = "GET_ALL_ITEMS_FAILURE";

export const GET_ONE_ITEM_STARTED = "GET_ONE_ITEM_STARTED";
export const GET_ONE_ITEM_SUCCESS = "GET_ONE_ITEM_SUCCESS";
export const GET_ONE_ITEM_FAILURE = "GET_ONE_ITEM_FAILURE";

export const UPDATE_ONE_ITEM_STARTED = "UPDATE_ONE_ITEM_STARTED";
export const UPDATE_ONE_ITEM_SUCCESS = "UPDATE_ONE_ITEM_SUCCESS";
export const UPDATE_ONE_ITEM_FAILURE = "UPDATE_ONE_ITEM_FAILURE";

export const REMOVE_ONE_ITEM = "REMOVE_ONE_ITEM";
