export const MenuData = [
	{
		id: 1,
		name: "Snack Set",
		img: require("./assets/snackset.avif"),
		ingredients: ["Butter", "cream", "honey", "salty, cottage cheese", "white cheese"],
		category: "Breakfast",
		availability: 5,
		weight: 160,
		vegetarian: false,
		cost: 8.2,
	},
	{
		id: 2,
		name: "Salmon and Avacado Bruchetta",
		img: require("./assets/avacado_bruchetta.avif"),
		ingredients: ["Black Bread", "Smoked Salmon", "Philadelphia cheese", "Avacado", "Tomato", "cheese"],
		category: "Lunch",
		availability: 7,
		weight: 180,
		vegetarian: true,
		cost: 12.5,
	},
	{
		id: 3,
		name: "Croque Madame",
		img: require("./assets/Croque_madame.avif"),
		ingredients: ["Toasted Bread", "Veal Salami", "cheese", "Eggs", "Carrot", "Gouda cheese"],
		category: "Dinner",
		availability: 5,
		weight: 150,
		vegetarian: false,
		cost: 9.5,
	},
	{
		id: 4,
		name: "Cheese Pancakes",
		img: require("./assets/cheese pancakes.avif"),
		ingredients: ["Puff Pastry", "Cheese Fillings", "Argula", "Cucumber", "Carrot", "Radish"],
		category: "Dinner",
		availability: 5,
		weight: 150,
		vegetarian: true,
		cost: 9.5,
	},
];
